[SQL_SELECT_BANKACCESS_BY_PRIMARY_ID]
${SQL_SELECT_BANKACCESS_BY_ID};

[SQL_SELECT_PSD2_CLIENT_CONFIGURATION_BY_PRIMARY_ID]
SELECT * FROM psd2ClientConfiguration WHERE id = ?;

[SQL_SELECT_BANKACCOUNT_BY_PRIMARY_ID]
SELECT * FROM bankAccount WHERE id = ?;

[SQL_SELECT_BANKACCOUNT_STATEMENT_BY_PRIMARY_ID]
SELECT * FROM bankAccountStatement WHERE id = ?;

[SQL_SELECT_BANK_MESSAGE_BY_PRIMARY_ID]
SELECT * FROM bankMessage WHERE id = ?;

[SQL_SELECT_BOOKING_BY_PRIMARY_ID]
SELECT * FROM bookingFull WHERE id = ?;

[SQL_SELECT_CATEGORY_BY_PRIMARY_ID]
SELECT * FROM categoryFull WHERE id = ?;

[SQL_SELECT_CATEGORYRULE_BY_PRIMARY_ID]
SELECT cgr.*, NULL AS categoryName, NULL AS fullName
FROM categoryRule cgr
WHERE cgr.id = ?;

[SQL_SELECT_MONEYTRANSFER_BY_PRIMARY_ID]
${SQL_SELECT_ALL_MONEYTRANSFERS_BASE} AND m.id = ?;

[SQL_SELECT_MONEYTRANSFER_FOREIGN_BY_PRIMARY_ID]
SELECT * FROM moneytransferForeign WHERE id = ?;

[SQL_SELECT_MONEYTRANSFER_PROTOCOL_BY_PRIMARY_ID]
SELECT * FROM moneytransferProtocol WHERE id = ?;

[SQL_SELECT_RECIPIENT_BY_PRIMARY_ID]
SELECT * FROM recipient WHERE id = ?;

[SQL_SELECT_PARAMETERDATA_BY_PRIMARY_ID]
SELECT * FROM parameterData WHERE id = ?;

[SQL_SELECT_INSTITUTE_BY_PRIMARY_ID]
${SQL_SELECT_ALL_INSTITUTES_BASE} WHERE i.id = ?;

[SQL_SELECT_IMPORT_HISTORY_BY_PRIMARY_ID]
SELECT * FROM institute_db.importHistory WHERE id = ?;

[SQL_SELECT_SETTING_BY_PRIMARY_ID]
SELECT * FROM setting WHERE id = ?;

[SQL_SELECT_BUSINESSCASE_BY_PRIMARY_ID]
SELECT * FROM businessCase WHERE id = ?;

[SQL_DELETE_BANKACCOUNT_BY_PRIMARY_ID]
DELETE FROM bankAccount WHERE id = ?;

[SQL_DELETE_PSD2_CLIENT_CONFIGURATION_BY_PRIMARY_ID]
DELETE FROM psd2ClientConfiguration WHERE id = ?;

[SQL_DELETE_BANKACCOUNT_STATEMENT_BY_PRIMARY_ID]
DELETE FROM bankAccountStatement WHERE id = ?;

[SQL_DELETE_BANK_MESSAGE_BY_PRIMARY_ID]
DELETE FROM bankMessage WHERE id = ?;

[SQL_DELETE_CATEGORYRULE_BY_PRIMARY_ID]
DELETE FROM categoryRule WHERE id = ?;

[SQL_DELETE_MONEYTRANSFER_BY_PRIMARY_ID]
DELETE FROM moneytransfer WHERE id = ?;

[SQL_DELETE_MONEYTRANSFER_PROTOCOL_BY_PRIMARY_ID]
DELETE FROM moneytransferProtocol WHERE id = ?;

[SQL_DELETE_RECIPIENT_BY_PRIMARY_ID]
DELETE FROM recipient WHERE id = ?;

[SQL_DELETE_PARAMETERDATA_BY_PRIMARY_ID]
DELETE FROM parameterData WHERE id = ?;

[SQL_DELETE_INSTITUTE_BY_PRIMARY_ID]
DELETE FROM institute_db.institute WHERE id = ?;

[SQL_DELETE_IMPORT_HISTORY_BY_PRIMARY_ID]
DELETE FROM institute_db.importHistory WHERE id = ?;

[SQL_DELETE_SETTING_BY_PRIMARY_ID]
DELETE FROM setting WHERE id = ?;

[SQL_DELETE_BUSINESSCASE_BY_PRIMARY_ID]
DELETE FROM businessCase WHERE id = ?;
