package de.gbanking.db;

public class SqlStatements {

    private SqlStatements() {
    }

    private static String dml(String key) {
        return SqlTemplateRepository.getDml(key);
    }

	static final String SQL_SELECT_ID_BANKACCESS_BY_BLZ = dml("SQL_SELECT_ID_BANKACCESS_BY_BLZ");
	static final String SQL_INSERT_BANKACCESS = dml("SQL_INSERT_BANKACCESS");
	static final String SQL_UPDATE_BANKACCESS = dml("SQL_UPDATE_BANKACCESS");
	static final String SQL_SELECT_ALL_BANKACCESSES = dml("SQL_SELECT_ALL_BANKACCESSES");
	static final String SQL_SELECT_BANKACCESS_BY_ID = dml("SQL_SELECT_BANKACCESS_BY_ID");
	static final String SQL_SELECT_BANKACCESS_BY_BLZ = dml("SQL_SELECT_BANKACCESS_BY_BLZ");
	static final String SQL_DELETE_BANKACCESS_BY_BLZ = dml("SQL_DELETE_BANKACCESS_BY_BLZ");
	static final String SQL_SELECT_ALL_PARAMETERDATA = dml("SQL_SELECT_ALL_PARAMETERDATA");
	static final String SQL_SELECT_ALL_BPD_OR_UPD = dml("SQL_SELECT_ALL_BPD_OR_UPD");
	public static final String SQL_INSERT_PARAMETERDATA = dml("SQL_INSERT_PARAMETERDATA");
	static final String SQL_UPDATE_PARAMETERDATA = dml("SQL_UPDATE_PARAMETERDATA");
	public static final String SQL_SELECT_ALL_PARAMETERDATA_BY_BANKACCESS = dml("SQL_SELECT_ALL_PARAMETERDATA_BY_BANKACCESS");
	public static final String SQL_INSERT_BANKACCESS_PARAMETERDATA = dml("SQL_INSERT_BANKACCESS_PARAMETERDATA");
	static final String SQL_UPDATE_BANKACCESS_PARAMETERDATA = dml("SQL_UPDATE_BANKACCESS_PARAMETERDATA");
    static final String SQL_DELETE_BANKACCESS_PARAMETERDATA = dml("SQL_DELETE_BANKACCESS_PARAMETERDATA");
    public static final String SQL_DELETE_ALL_BANKACCESS_PARAMETERDATA_BY_BANKACCESS = dml("SQL_DELETE_ALL_BANKACCESS_PARAMETERDATA_BY_BANKACCESS");
    public static final String SQL_DELETE_UNUSED_PARAMETERDATA = dml("SQL_DELETE_UNUSED_PARAMETERDATA");
    public static final String SQL_SELECT_ALL_BUSINESSCASES = dml("SQL_SELECT_ALL_BUSINESSCASES");
    public static final String SQL_SELECT_ALL_BUSINESSCASES_BY_BANKACCOUNT = dml("SQL_SELECT_ALL_BUSINESSCASES_BY_BANKACCOUNT");
    public static final String SQL_INSERT_BUSINESSCASE = dml("SQL_INSERT_BUSINESSCASE");
    public static final String SQL_INSERT_BANKACCOUNT_BUSINESSCASE = dml("SQL_INSERT_BANKACCOUNT_BUSINESSCASE");
    static final String SQL_SELECT_ID_BANKACCOUNT_BY_IBAN_OR_NUMBER = dml("SQL_SELECT_ID_BANKACCOUNT_BY_IBAN_OR_NUMBER");
    static final String SQL_INSERT_BANKACCOUNT = dml("SQL_INSERT_BANKACCOUNT");
    static final String SQL_UPDATE_BANKACCOUNT = dml("SQL_UPDATE_BANKACCOUNT");
    static final String SQL_UPDATE_BANKACCOUNT_SOURCE = dml("SQL_UPDATE_BANKACCOUNT_SOURCE");
    static final String SQL_SELECT_ALL_BANKACCOUNTS = dml("SQL_SELECT_ALL_BANKACCOUNTS");
    static final String SQL_SELECT_ALL_BANKACCOUNTS_BY_BANKACCESS = dml("SQL_SELECT_ALL_BANKACCOUNTS_BY_BANKACCESS");
    static final String SQL_SELECT_ACCOUNT_LAST_BOOKING_DATE = dml("SQL_SELECT_ACCOUNT_LAST_BOOKING_DATE");
    static final String SQL_SELECT_ID_MONEYTRANSFER_BY_ID_AND_ACCOUNT_ID = dml("SQL_SELECT_ID_MONEYTRANSFER_BY_ID_AND_ACCOUNT_ID");
    static final String SQL_INSERT_MONEYTRANSFER = dml("SQL_INSERT_MONEYTRANSFER");
    static final String SQL_UPDATE_MONEYTRANSFER = dml("SQL_UPDATE_MONEYTRANSFER");
    static final String SQL_SELECT_ALL_MONEYTRANSFERS_BY_ACCOUNT = dml("SQL_SELECT_ALL_MONEYTRANSFERS_BY_ACCOUNT");
    static final String SQL_SELECT_ALL_MONEYTRANSFERS = dml("SQL_SELECT_ALL_MONEYTRANSFERS");
    static final String SQL_SELECT_ALL_MONEYTRANSFERS_WITH_RECIPIENTS_BY_ACCOUNT = dml("SQL_SELECT_ALL_MONEYTRANSFERS_WITH_RECIPIENTS_BY_ACCOUNT");
    static final String SQL_SELECT_ALL_MONEYTRANSFERS_WITH_RECIPIENTS_BY_STATE = dml("SQL_SELECT_ALL_MONEYTRANSFERS_WITH_RECIPIENTS_BY_STATE");
    static final String SQL_SELECT_ALL_MONEYTRANSFERS_WITH_RECIPIENTS_BY_ACCOUNT_AND_STATE = dml("SQL_SELECT_ALL_MONEYTRANSFERS_WITH_RECIPIENTS_BY_ACCOUNT_AND_STATE");
    static final String SQL_DELETE_MONEYTRANSFER_BY_ID = dml("SQL_DELETE_MONEYTRANSFER_BY_ID");
    public static final String SQL_INSERT_RECIPIENT = dml("SQL_INSERT_RECIPIENT");
    public static final String SQL_UPDATE_RECIPIENT = dml("SQL_UPDATE_RECIPIENT");
    public static final String SQL_UPDATE_RECIPIENT_NOTE = dml("SQL_UPDATE_RECIPIENT_NOTE");
    public static final String SQL_SELECT_ID_RECIPIENT_BY_IBAN = dml("SQL_SELECT_ID_RECIPIENT_BY_IBAN");
    static final String SQL_SELECT_ALL_RECIPIENTS = dml("SQL_SELECT_ALL_RECIPIENTS");
    static final String SQL_SELECT_ALL_RECIPIENTS_WITH_NAME_IBAN = dml("SQL_SELECT_ALL_RECIPIENTS_WITH_NAME_IBAN");
    static final String SQL_SELECT_RECIPIENT_BY_ID = dml("SQL_SELECT_RECIPIENT_BY_ID");
    static final String SQL_FIND_RECIPIENT_BY_ARGS = dml("SQL_FIND_RECIPIENT_BY_ARGS");
    private static final String SQL_WHERE_RECIPIENT_BY_ID_IF_NOT_REFERENCED = dml("SQL_WHERE_RECIPIENT_BY_ID_IF_NOT_REFERENCED");
    static final String SQL_DELETE_RECIPIENT_BY_ID_IF_NOT_REFERENCED = dml("SQL_DELETE_RECIPIENT_BY_ID_IF_NOT_REFERENCED");
    public static final String SQL_SELECT_RECIPIENT_BY_ID_IF_NOT_REFERENCED = dml("SQL_SELECT_RECIPIENT_BY_ID_IF_NOT_REFERENCED");
    static final String SQL_UPDATE_RECIPIENT_IF_NOT_REFERENCED = dml("SQL_UPDATE_RECIPIENT_IF_NOT_REFERENCED");
    public static final String SQL_INSERT_CATEGORY = dml("SQL_INSERT_CATEGORY");
    static final String SQL_UPDATE_CATEGORY = dml("SQL_UPDATE_CATEGORY");
    static final String SQL_SELECT_ID_CATEGORY_BY_NAME = dml("SQL_SELECT_ID_CATEGORY_BY_NAME");
    static final String SQL_SELECT_ALL_CATEGORIES = dml("SQL_SELECT_ALL_CATEGORIES");
    static final String SQL_FIND_CATEGORY = dml("SQL_FIND_CATEGORY");
    private static final String SQL_SELECT_CATEGORY_RECURSIVE_WITH = dml("SQL_SELECT_CATEGORY_RECURSIVE_WITH");
    static final String SQL_SELECT_ALL_CATEGORIES_FULL = dml("SQL_SELECT_ALL_CATEGORIES_FULL");
    static final String SQL_SELECT_CATEGORY_FULL_BY_NAME = dml("SQL_SELECT_CATEGORY_FULL_BY_NAME");
    static final String SQL_DELETE_CATEGORY = dml("SQL_DELETE_CATEGORY");
	static final String SQL_SELECT_ID_CATEGORYRULE = dml("SQL_SELECT_ID_CATEGORYRULE");
	static final String SQL_SELECT_ALL_CATEGORYRULES = dml("SQL_SELECT_ALL_CATEGORYRULES");
	static final String SQL_INSERT_CATEGORYRULE = dml("SQL_INSERT_CATEGORYRULE");
	static final String SQL_UPDATE_CATEGORYRULE = dml("SQL_UPDATE_CATEGORYRULE");
	static final String SQL_SELECT_ALL_CATEGORYRULE_BANKACCOUNT = dml("SQL_SELECT_ALL_CATEGORYRULE_BANKACCOUNT");
	static final String SQL_INSERT_CATEGORYRULE_BANKACCOUNT = dml("SQL_INSERT_CATEGORYRULE_BANKACCOUNT");
	static final String SQL_UPDATE_CATEGORYRULE_BANKACCOUNT = dml("SQL_UPDATE_CATEGORYRULE_BANKACCOUNT");
    static final String SQL_SELECT_ID_BOOKING = dml("SQL_SELECT_ID_BOOKING");
    static final String SQL_INSERT_BOOKING = dml("SQL_INSERT_BOOKING");
    static final String SQL_UPDATE_BOOKING = dml("SQL_UPDATE_BOOKING");
    static final String SQL_SELECT_ALL_BOOKINGS = dml("SQL_SELECT_ALL_BOOKINGS");
    static final String SQL_SELECT_ALL_BOOKINGS_BY_ACCOUNT = dml("SQL_SELECT_ALL_BOOKINGS_BY_ACCOUNT");
    static final String SQL_SELECT_ALL_BOOKINGS_FULL = dml("SQL_SELECT_ALL_BOOKINGS_FULL");
    static final String SQL_SELECT_ALL_BOOKINGS_WITH_BALANCE = dml("SQL_SELECT_ALL_BOOKINGS_WITH_BALANCE");
    static final String SQL_SELECT_ALL_BOOKINGS_FULL_BY_ACCOUNT = dml("SQL_SELECT_ALL_BOOKINGS_FULL_BY_ACCOUNT");
    static final String SQL_FIND_CROSS_BOOKINGS_FULL = dml("SQL_FIND_CROSS_BOOKINGS_FULL");
    static final String SQL_UPDATE_BOOKINGS_SOURCE = dml("SQL_UPDATE_BOOKINGS_SOURCE");
    static final String SQL_UPDATE_BOOKINGS_RECIPIENT = dml("SQL_UPDATE_BOOKINGS_RECIPIENT");
    static final String SQL_UPDATE_BOOKINGS_CATEGORY = dml("SQL_UPDATE_BOOKINGS_CATEGORY");
    static final String SQL_INSERT_MONEYTRANSFER_PROTOCOL = dml("SQL_INSERT_MONEYTRANSFER_PROTOCOL");
    private static final String INSTITUTE_FIELD_LIST = dml("INSTITUTE_FIELD_LIST");
    static final String SQL_SELECT_ALL_INSTITUTES = dml("SQL_SELECT_ALL_INSTITUTES");
    static final String SQL_SELECT_ID_INSTIUTE_BY_ID = dml("SQL_SELECT_ID_INSTIUTE_BY_ID");
    static final String SQL_SELECT_ID_INSTIUTE_BY_BLZ = dml("SQL_SELECT_ID_INSTIUTE_BY_BLZ");
    static final String SQL_INSERT_INSTIUTE = dml("SQL_INSERT_INSTIUTE");
    static final String SQL_UPDATE_INSTIUTE = dml("SQL_UPDATE_INSTIUTE");
    private static final String SETTING_FIELD_LIST = dml("SETTING_FIELD_LIST");
    static final String SQL_SELECT_ALL_SETTINGS = dml("SQL_SELECT_ALL_SETTINGS");
    static final String SQL_SELECT_ID_SETTING_BY_ID = dml("SQL_SELECT_ID_SETTING_BY_ID");
    static final String SQL_SELECT_ID_SETTING_BY_ATTRIBUTE = dml("SQL_SELECT_ID_SETTING_BY_ATTRIBUTE");
    static final String SQL_INSERT_SETTING = dml("SQL_INSERT_SETTING");
    static final String SQL_UPDATE_SETTING = dml("SQL_UPDATE_SETTING");
}
