package de.gbanking.db;

class SqlStatementsDDL {

    private SqlStatementsDDL() {
    }

    private static String ddl(String key) {
        return SqlTemplateRepository.getDdl(key);
    }

    static final String SQL_FOREIGN_KEY_CHECKS_ON = ddl("SQL_FOREIGN_KEY_CHECKS_ON");
    static final String SQL_SETUP_DROP_BANKACCESS = ddl("SQL_SETUP_DROP_BANKACCESS");
    static final String SQL_SETUP_DROP_BANKACCOUNT = ddl("SQL_SETUP_DROP_BANKACCOUNT");
    static final String SQL_SETUP_DROP_BOOKING = ddl("SQL_SETUP_DROP_BOOKING");
    static final String SQL_SETUP_DROP_BUSINESSCASE = ddl("SQL_SETUP_DROP_BUSINESSCASE");
    static final String SQL_SETUP_DROP_MONEYTRANSFER = ddl("SQL_SETUP_DROP_MONEYTRANSFER");
    static final String SQL_SETUP_DROP_RECIPIENT = ddl("SQL_SETUP_DROP_RECIPIENT");
    static final String SQL_SETUP_DROP_CATEGORY = ddl("SQL_SETUP_DROP_CATEGORY");
    static final String SQL_SETUP_DROP_CATEGORY_RULE = ddl("SQL_SETUP_DROP_CATEGORY_RULE");
    static final String SQL_SETUP_DROP_CATEGORY_RULE_BANKACCOUNT = ddl("SQL_SETUP_DROP_CATEGORY_RULE_BANKACCOUNT");
    static final String SQL_SETUP_DROP_MONEYTRANSFER_PROTOCOL = ddl("SQL_SETUP_DROP_MONEYTRANSFER_PROTOCOL");
    static final String SQL_SETUP_DROP_BANKACCOUNT_BUSINESSCASE = ddl("SQL_SETUP_DROP_BANKACCOUNT_BUSINESSCASE");
    static final String SQL_SETUP_DROP_PARAMETERDATA = ddl("SQL_SETUP_DROP_PARAMETERDATA");
    static final String SQL_SETUP_DROP_BANKACCESS_PARAMETERDATA = ddl("SQL_SETUP_DROP_BANKACCESS_PARAMETERDATA");
    static final String SQL_SETUP_DROP_INSTITUTE = ddl("SQL_SETUP_DROP_INSTITUTE");
    static final String SQL_SETUP_DROP_SETTING = ddl("SQL_SETUP_DROP_SETTING");
    static final String SQL_SETUP_DROP_BOOKING_CATEGORY = ddl("SQL_SETUP_DROP_BOOKING_CATEGORY");
    static final String SQL_SETUP_DROP_UNIQUE_INDEX_INSTITUTE = ddl("SQL_SETUP_DROP_UNIQUE_INDEX_INSTITUTE");
	static final String SQL_SETUP_DROP_VIEW_CATEGORY_FULL = ddl("SQL_SETUP_DROP_VIEW_CATEGORY_FULL");
	static final String SQL_SETUP_DROP_VIEW_BPD = ddl("SQL_SETUP_DROP_VIEW_BPD");
	static final String SQL_SETUP_DROP_VIEW_UPD = ddl("SQL_SETUP_DROP_VIEW_UPD");
    static final String SQL_SETUP_CREATE_BANKACCESS = ddl("SQL_SETUP_CREATE_BANKACCESS");
    static final String SQL_SETUP_CREATE_BANKACCOUNT = ddl("SQL_SETUP_CREATE_BANKACCOUNT");
    static final String SQL_SETUP_CREATE_BOOKING = ddl("SQL_SETUP_CREATE_BOOKING");
    static final String SQL_SETUP_CREATE_BUSINESSCASE = ddl("SQL_SETUP_CREATE_BUSINESSCASE");
    static final String SQL_SETUP_CREATE_MONEYTRANSFER = ddl("SQL_SETUP_CREATE_MONEYTRANSFER");
    static final String SQL_SETUP_CREATE_RECIPIENT = ddl("SQL_SETUP_CREATE_RECIPIENT");
    static final String SQL_SETUP_CREATE_CATEGORY = ddl("SQL_SETUP_CREATE_CATEGORY");
    static final String SQL_SETUP_CREATE_CATEGORY_RULE = ddl("SQL_SETUP_CREATE_CATEGORY_RULE");
    static final String SQL_SETUP_CREATE_CATEGORY_RULE_BANKACCOUNT = ddl("SQL_SETUP_CREATE_CATEGORY_RULE_BANKACCOUNT");
    static final String SQL_SETUP_CREATE_MONEYTRANSFER_PROTOCOL = ddl("SQL_SETUP_CREATE_MONEYTRANSFER_PROTOCOL");
    static final String SQL_SETUP_CREATE_BANKACCOUNT_BUSINESSCASE = ddl("SQL_SETUP_CREATE_BANKACCOUNT_BUSINESSCASE");
    static final String SQL_SETUP_CREATE_PARAMETERDATA = ddl("SQL_SETUP_CREATE_PARAMETERDATA");
    static final String SQL_SETUP_CREATE_BANKACCESS_PARAMETERDATA = ddl("SQL_SETUP_CREATE_BANKACCESS_PARAMETERDATA");
    static final String SQL_SETUP_CREATE_INSTITUTE = ddl("SQL_SETUP_CREATE_INSTITUTE");
    static final String SQL_SETUP_CREATE_UNIQUE_INDEX_INSTITUTE = ddl("SQL_SETUP_CREATE_UNIQUE_INDEX_INSTITUTE");
    static final String SQL_SETUP_CREATE_SETTING = ddl("SQL_SETUP_CREATE_SETTING");
    static final String SQL_SETUP_CREATE_BOOKING_CATEGORY = ddl("SQL_SETUP_CREATE_BOOKING_CATEGORY");
	static final String SQL_SETUP_VIEW_CATEGORY_FULL = ddl("SQL_SETUP_VIEW_CATEGORY_FULL");
	static final String SQL_SETUP_VIEW_BPD = ddl("SQL_SETUP_VIEW_BPD");
	static final String SQL_SETUP_VIEW_UPD = ddl("SQL_SETUP_VIEW_UPD");

    static final String SQL_SETUP_INSERT_SETTING_DEFAULT_VALUES = ddl("SQL_SETUP_INSERT_SETTING_DEFAULT_VALUES");
}
