DROP INDEX IF EXISTS idx_bankaccess_blz_user;
DROP INDEX IF EXISTS idx_bankaccount_bankaccess;
DROP INDEX IF EXISTS idx_bankaccount_parent;
DROP INDEX IF EXISTS idx_bankaccount_iban;
DROP INDEX IF EXISTS idx_bankaccount_number;
DROP INDEX IF EXISTS idx_bankaccountstatement_account;
DROP INDEX IF EXISTS idx_bankaccountstatement_order;
DROP INDEX IF EXISTS idx_bankmessage_bankaccess;
DROP INDEX IF EXISTS idx_bankmessage_order;
DROP INDEX IF EXISTS idx_booking_account;
DROP INDEX IF EXISTS idx_booking_account_root_id;
DROP INDEX IF EXISTS idx_booking_account_root_effective_date;
DROP INDEX IF EXISTS idx_booking_account_root_source_date;
DROP INDEX IF EXISTS idx_booking_account_root_amount_date;
DROP INDEX IF EXISTS idx_booking_parent;
DROP INDEX IF EXISTS idx_booking_recipient_usage;
DROP INDEX IF EXISTS idx_booking_cross_booking;
DROP INDEX IF EXISTS idx_booking_category_category;
DROP INDEX IF EXISTS idx_bankaccount_businesscase_businesscase;
DROP INDEX IF EXISTS idx_categoryrule_bankaccount_account;
DROP INDEX IF EXISTS idx_moneytransfer_account_status;
DROP INDEX IF EXISTS idx_moneytransfer_status;
DROP INDEX IF EXISTS idx_moneytransfer_recipient_usage;
DROP INDEX IF EXISTS idx_moneytransfer_history;
DROP INDEX IF EXISTS idx_moneytransferprotocol_transfer;
DROP INDEX IF EXISTS idx_bankaccess_parameterdata_parameter;
CREATE INDEX idx_bankaccountstatement_account ON bankAccountStatement (account_id, statementDate, retrievedAt);
CREATE INDEX idx_bankmessage_bankaccess ON bankMessage (bankAccess_id, versionDate, retrievedAt);
CREATE INDEX idx_booking_recipient_id ON booking (recipient_id);
CREATE UNIQUE INDEX uk_booking_category ON booking_category (booking_id, category_id);
CREATE UNIQUE INDEX uk_bankaccount_businesscase ON bankAccount_businessCase (account_id, businessCase_id);
CREATE UNIQUE INDEX uk_categoryrule_bankaccount ON categoryRule_bankAccount (categoryRule_id, account_id);
CREATE UNIQUE INDEX uk_parameterdata_type_key ON parameterData (pdType, pdKey);
CREATE UNIQUE INDEX uk_bankaccess_parameterdata ON bankAccess_parameterData (bankAccess_id, parameterData_id);
CREATE INDEX idx_moneytransfer_recipient_id ON moneytransfer (recipient_id);
CREATE INDEX idx_moneytransferforeign_moneytransfer_id ON moneytransferForeign (moneytransfer_id);
