
[Buchung: GBanking]
Konto.Name=KONTO_NAME
Konto.Iban=KONTO_IBAN
Konto.Nummer=KONTO_NR
Konto.Bank=KONTO_BANK
Konto.Bic=KONTO_BIC
Datum=BUCHUNGSDATUM
Valuta=WERTSTELLUNG
Betrag=BETRAG
Waehrung=WAEHRUNG
Zweck=VERWENDUNGSZWECK
Name=EMPFAENGER_NAME
Iban=EMPFAENGER_IBAN
Bic=EMPFAENGER_BIC
Empfaenger.Kontonummer=EMPFAENGER_KONTONR
Empfaenger.Blz=EMPFAENGER_BLZ
Empfaenger.Bank=EMPFAENGER_BANK
Buchungstyp=BUCHUNGSTYP
Hauptkategorie=KATEGORIE
Sepa.Kundenreferenz=SEPA_CUSTOMER_REF
Sepa.GlaeubigerId=SEPA_CREDITOR_ID
Sepa.EndToEnd=SEPA_END_TO_END
Sepa.Mandat=SEPA_MANDATE
Sepa.PersonenId=SEPA_PERSON_ID
Sepa.Zweck=SEPA_PURPOSE
Sepa.Typ=SEPA_TYPE
Format.DecimalSeparator=auto
Default.Waehrung=EUR
Dialog.Filter=CSV-Datei|*.csv
Dialog.DefaultExt=csv
Dialog.Filename=*.csv

[Buchung: Kreditkarte Instabank]
Datum=Datum
Valuta=Wertstellungsdatum
Zweck=Beschreibung
Betrag=Auf das Konto;Aus dem Konto
Format.DecimalSeparator=auto
Default.Waehrung=EUR
Dialog.Filter=CSV-Datei|*.csv
Dialog.DefaultExt=csv
Dialog.Filename=*.csv

[Buchung: Kreditkarte Bank Norwegian]
Datum=BookDate
Valuta=ValueDate
Zweck=Text
Betrag=Amount
Kreditkarte.Transaktionsdatum=TransactionDate
Kreditkarte.Typ=Type
Kreditkarte.Waehrungsbetrag=Currency Amount
Kreditkarte.Wechselkurs=Currency Rate
Kreditkarte.Waehrung=Currency
Kreditkarte.Haendlerregion=Merchant Area
Kreditkarte.Haendlerkategorie=Merchant Category
Format.DecimalSeparator=auto
Default.Waehrung=EUR
Dialog.Filter=CSV-Datei|*.csv
Dialog.DefaultExt=csv
Dialog.Filename=*.csv

[Buchung: VR-NetWorld]
Konto.Name=Kontoname
Konto.Nummer=Kontonummer
Datum=Datum
Valuta=Valuta
Name=Zahlungspflichtiger/-empfänger
Iban=ZP/ZE Konto/IBAN
Bic=ZP/ZE Bankleitzahl/BIC
Zweck=Verwendungszweck
Hauptkategorie=Kategorie
Betrag=Betrag
Waehrung=Währung
Quellfeld.Bankleitzahl=Bankleitzahl
Format.DateOrder=TMJ
Format.DecimalSeparator=,
Format.ThousandSeparator=.
Dialog.Filter=CSV-Datei|*.csv
Dialog.DefaultExt=csv
Dialog.Filename=*.csv

[Buchung: DKB Web]
Datum=Buchungsdatum
Valuta=Wertstellung
Name=Zahlungsempfänger*in
Iban=IBAN
Zweck=Verwendungszweck
Buchungstyp=Umsatztyp
Betrag=Betrag (€)
Sepa.GlaeubigerId=Gläubiger-ID
Sepa.Mandat=Mandatsreferenz
Sepa.Kundenreferenz=Kundenreferenz
Quellfeld.Status=Status
Quellfeld.Zahlungspflichtiger=Zahlungspflichtige*r
Ignore.LeadingRows=3
Format.DateOrder=TMJ
Format.DecimalSeparator=,
Format.ThousandSeparator=.
Default.Waehrung=EUR
Dialog.Filter=CSV-Datei|*.csv
Dialog.DefaultExt=csv
Dialog.Filename=*.csv

[Buchung: N26 Deutsch]
Datum=Datum
Name=Empfänger
Iban=Kontonummer
Buchungstyp=Transaktionstyp
Zweck=Verwendungszweck
Hauptkategorie=Kategorie
Betrag=Betrag (EUR)
Kreditkarte.Waehrungsbetrag=Betrag (Fremdwährung)
Kreditkarte.Waehrung=Fremdwährung
Kreditkarte.Wechselkurs=Wechselkurs
Extra.Separator=,
Format.DateOrder=JMT
Format.DecimalSeparator=.
Format.ThousandSeparator=,
Default.Waehrung=EUR
Dialog.Filter=CSV-Datei|*.csv
Dialog.DefaultExt=csv
Dialog.Filename=*.csv

[Buchung: N26 English]
Datum=Date
Name=Payee
Iban=Account number
Buchungstyp=Transaction type
Zweck=Payment reference
Hauptkategorie=Category
Betrag=Amount (EUR)
Kreditkarte.Waehrungsbetrag=Amount (Foreign Currency)
Kreditkarte.Waehrung=Type Foreign Currency
Kreditkarte.Wechselkurs=Exchange Rate
Extra.Separator=,
Format.DateOrder=JMT
Format.DecimalSeparator=.
Format.ThousandSeparator=,
Default.Waehrung=EUR
Dialog.Filter=CSV file|*.csv
Dialog.DefaultExt=csv
Dialog.Filename=*.csv

[Buchung: Commerzbank Web]
Konto.Iban=IBAN Kontoinhaber
Datum=Buchungstag
Valuta=Wertstellung
Buchungstyp=Umsatzart
Zweck=Buchungstext;Umsatzart
Betrag=Betrag
Waehrung=Währung
Hauptkategorie=Kategorie
Format.DateOrder=TMJ
Format.DecimalSeparator=,
Format.ThousandSeparator=.
Dialog.Filter=CSV-Datei|*.csv
Dialog.DefaultExt=csv
Dialog.Filename=*.csv

[Buchung: Commerzbank Web erweitert]
Konto.Iban=IBAN Kontoinhaber
Datum=Buchungstag
Valuta=Wertstellung
Buchungstyp=Umsatzart
Zweck=Buchungstext;Umsatzart;Verwendungszweck
Betrag=Betrag
Waehrung=Währung
Hauptkategorie=Kategorie
Quellfeld.Sender=Sender
Quellfeld.Empfaenger=Empfänger
Format.DateOrder=TMJ
Format.DecimalSeparator=,
Format.ThousandSeparator=.
Dialog.Filter=CSV-Datei|*.csv
Dialog.DefaultExt=csv
Dialog.Filename=*.csv

[Buchung: Atruvia VR-Banken und GLS]
Konto.Name=Bezeichnung Auftragskonto
Konto.Iban=IBAN Auftragskonto
Konto.Bic=BIC Auftragskonto
Konto.Bank=Bankname Auftragskonto
Datum=Buchungstag
Valuta=Valutadatum
Name=Name Zahlungsbeteiligter
Iban=IBAN Zahlungsbeteiligter
Bic=BIC (SWIFT-Code) Zahlungsbeteiligter
Buchungstyp=Buchungstext
Zweck=Verwendungszweck;Bemerkung
Betrag=Betrag
Waehrung=Waehrung
Sepa.GlaeubigerId=Glaeubiger ID
Sepa.Mandat=Mandatsreferenz
Quellfeld.Saldo=Saldo nach Buchung
Quellfeld.Gekennzeichnet=Gekennzeichneter Umsatz
Format.DateOrder=TMJ
Format.DecimalSeparator=,
Format.ThousandSeparator=.
Dialog.Filter=CSV-Datei|*.csv
Dialog.DefaultExt=csv
Dialog.Filename=*.csv

[Buchung: Sparda-Bank West]
Konto.Name=Bezeichnung Auftragskonto
Konto.Iban=IBAN Auftragskonto
Konto.Bic=BIC Auftragskonto
Konto.Bank=Bankname Auftragskonto
Datum=Buchungstag
Valuta=Valutadatum
Name=Name Zahlungsbeteiligter
Iban=IBAN Zahlungsbeteiligter
Bic=BIC (SWIFT-Code) Zahlungsbeteiligter
Buchungstyp=Buchungstext
Zweck=Verwendungszweck;Bemerkung
Betrag=Betrag
Waehrung=Währung
Sepa.GlaeubigerId=Gläubiger ID
Sepa.Mandat=Mandatsreferenz
Quellfeld.Saldo=Saldo nach Buchung
Quellfeld.Gekennzeichnet=Gekennzeichneter Umsatz
Format.DateOrder=TMJ
Format.DecimalSeparator=,
Format.ThousandSeparator=.
Dialog.Filter=CSV-Datei|*.csv
Dialog.DefaultExt=csv
Dialog.Filename=*.csv

[Buchung: Postbank Web]
Datum=Buchungstag
Valuta=Wert
Buchungstyp=Umsatzart
Name=Begünstigter / Auftraggeber
Zweck=Verwendungszweck
Iban=IBAN / Kontonummer
Bic=BIC
Sepa.Kundenreferenz=Kundenreferenz
Sepa.Mandat=Mandatsreferenz
Sepa.GlaeubigerId=Gläubiger ID
Betrag=Haben;Soll
Waehrung=Währung
Quellfeld.FremdeGebuehren=Fremde Gebühren
Quellfeld.Betrag=Betrag
Quellfeld.AbweichenderEmpfaenger=Abweichender Empfänger
Quellfeld.AnzahlAuftraege=Anzahl der Aufträge
Quellfeld.AnzahlSchecks=Anzahl der Schecks
Ignore.LeadingRows=7
Format.DateOrder=TMJ
Format.DecimalSeparator=,
Format.ThousandSeparator=.
Default.Waehrung=EUR
Dialog.Filter=CSV-Datei|*.csv
Dialog.DefaultExt=csv
Dialog.Filename=*.csv

[Buchung: Vivid]
Datum=Completed date
Name=Counterparty name
Zweck=Reference
Betrag=Payment amount
Waehrung=Payment currency
Extra.Separator=,
Format.DateOrder=TMJ
Format.DecimalSeparator=.
Format.ThousandSeparator=,
Dialog.Filter=CSV file|*.csv
Dialog.DefaultExt=csv
Dialog.Filename=*.csv
