[SQL_SETUP_DROP_VIEW_BPD]
DROP VIEW IF EXISTS bpd;

[SQL_SETUP_DROP_VIEW_UPD]
DROP VIEW IF EXISTS upd;

[SQL_SETUP_DROP_PARAMETERDATA]
DROP TABLE IF EXISTS parameterData;

[SQL_SETUP_DROP_BANKACCESS_PARAMETERDATA]
DROP TABLE IF EXISTS bankAccess_parameterData;

[SQL_SETUP_VIEW_BPD]
CREATE VIEW bpd AS ${SQL_SELECT_PD} 'BPD';

[SQL_SETUP_VIEW_UPD]
CREATE VIEW upd AS ${SQL_SELECT_PD} 'UPD';

[SQL_SETUP_CREATE_PARAMETERDATA]
CREATE TABLE parameterData (
  id INTEGER PRIMARY KEY,
  pdKey TEXT,
  pdType TEXT,
  updatedAt TEXT NOT NULL
  CHECK (pdType IN ("BPD", "UPD")));

[SQL_SETUP_CREATE_BANKACCESS_PARAMETERDATA]
CREATE TABLE bankAccess_parameterData (
  id INTEGER PRIMARY KEY,
  bankAccess_id INTEGER,
  parameterData_id INTEGER,
  pdValue TEXT,
  updatedAt TEXT NOT NULL,
  FOREIGN KEY(bankAccess_id) REFERENCES bankAccess(id) ON DELETE CASCADE,
  FOREIGN KEY(parameterData_id) REFERENCES parameterData(id) ON DELETE CASCADE);
  