package de.zft2.gbanking.db;

import java.util.Map;

import de.zft2.gbanking.db.StatementsConfig.StatementType;
import de.zft2.gbanking.db.dao.enu.ParameterDataType;

public final class DaoSqlStatements {

    private DaoSqlStatements() {
        /* This utility class should not be instantiated */
    }

	static String dml(String key) {
		if (key == null)
			return null;
        return SqlTemplateRepository.getDml(key);
    }

    static final String SQL_DELETE_BANKACCESS_BY_ID = dml("SQL_DELETE_BANKACCESS_BY_ID");
	public static final String SQL_DELETE_BANKACCESS_ENABLEBANKING = dml("SQL_DELETE_BANKACCESS_ENABLEBANKING");
	public static final String SQL_DELETE_BANKACCESS_FINTS = dml("SQL_DELETE_BANKACCESS_FINTS");
	public static final String SQL_DELETE_BANKACCESS_PAYPAL = dml("SQL_DELETE_BANKACCESS_PAYPAL");
    static final String SQL_FIND_CATEGORY = dml("SQL_FIND_CATEGORY");
    public static final String SQL_FIND_CROSS_BOOKINGS_FULL = dml("SQL_FIND_CROSS_BOOKINGS_FULL");
    static final String SQL_FIND_RECIPIENT_BY_ARGS = dml("SQL_FIND_RECIPIENT_BY_ARGS");
    static final String SQL_INSERT_BANKACCESS = dml("SQL_INSERT_BANKACCESS");
	static final String SQL_INSERT_PSD2_CLIENT_CONFIGURATION = dml("SQL_INSERT_PSD2_CLIENT_CONFIGURATION");
    static final String SQL_INSERT_BANKACCOUNT = dml("SQL_INSERT_BANKACCOUNT");
	static final String SQL_INSERT_BANKACCOUNT_IDENTIFIER = dml("SQL_INSERT_BANKACCOUNT_IDENTIFIER");
    static final String SQL_INSERT_BANKACCOUNT_STATEMENT = dml("SQL_INSERT_BANKACCOUNT_STATEMENT");
    static final String SQL_INSERT_BANK_MESSAGE = dml("SQL_INSERT_BANK_MESSAGE");
    public static final String SQL_INSERT_BANKACCESS_PARAMETERDATA = dml("SQL_INSERT_BANKACCESS_PARAMETERDATA");
    public static final String SQL_INSERT_BANKACCOUNT_BUSINESSCASE = dml("SQL_INSERT_BANKACCOUNT_BUSINESSCASE");
    static final String SQL_INSERT_BOOKING = dml("SQL_INSERT_BOOKING");
    public static final String SQL_INSERT_BOOKING_ADDITIONAL = dml("SQL_INSERT_BOOKING_ADDITIONAL");
	public static final String SQL_INSERT_BOOKING_ADDITIONAL_NOTE = dml("SQL_INSERT_BOOKING_ADDITIONAL_NOTE");
	public static final String SQL_INSERT_BOOKING_ADDITIONAL_CREDITCARD = dml("SQL_INSERT_BOOKING_ADDITIONAL_CREDITCARD");
	public static final String SQL_INSERT_BOOKING_ADDITIONAL_FOREIGNCURRENCY = dml("SQL_INSERT_BOOKING_ADDITIONAL_FOREIGNCURRENCY");
	public static final String SQL_INSERT_BOOKING_FEE = dml("SQL_INSERT_BOOKING_FEE");
	public static final String SQL_INSERT_BOOKING_ADDITIONAL_SEPA = dml("SQL_INSERT_BOOKING_ADDITIONAL_SEPA");
    public static final String SQL_INSERT_BUSINESSCASE = dml("SQL_INSERT_BUSINESSCASE");
    static final String SQL_INSERT_CATEGORY = dml("SQL_INSERT_CATEGORY");
    static final String SQL_INSERT_CATEGORYRULE = dml("SQL_INSERT_CATEGORYRULE");
    public static final String SQL_INSERT_CATEGORYRULE_BANKACCOUNT = dml("SQL_INSERT_CATEGORYRULE_BANKACCOUNT");
    static final String SQL_INSERT_IMPORT_HISTORY = dml("SQL_INSERT_IMPORT_HISTORY");
    static final String SQL_INSERT_INSTIUTE = dml("SQL_INSERT_INSTIUTE");
	public static final String SQL_INSERT_INSTITUTE_DK = dml("SQL_INSERT_INSTITUTE_DK");
	public static final String SQL_INSERT_INSTITUTE_DBB = dml("SQL_INSERT_INSTITUTE_DBB");
	public static final String SQL_INSERT_INSTITUTE_EPC = dml("SQL_INSERT_INSTITUTE_EPC");
	public static final String SQL_INSERT_INSTITUTE_DBB_REACHABLE = dml("SQL_INSERT_INSTITUTE_DBB_REACHABLE");
	public static final String SQL_INSERT_INSTITUTE_ADDITIONAL = dml("SQL_INSERT_INSTITUTE_ADDITIONAL");
	public static final String SQL_DELETE_INSTIUTE_DK = dml("SQL_DELETE_INSTITUTE_DK");
	public static final String SQL_DELETE_INSTIUTE_DBB = dml("SQL_DELETE_INSTITUTE_DBB");
	public static final String SQL_DELETE_INSTIUTE_EPC = dml("SQL_DELETE_INSTITUTE_EPC");
	public static final String SQL_DELETE_INSTIUTE_DBB_REACHABLE = dml("SQL_DELETE_INSTITUTE_DBB_REACHABLE");
	public static final String SQL_DELETE_INSTIUTE_ADDITIONAL = dml("SQL_DELETE_INSTITUTE_ADDITIONAL");
    static final String SQL_INSERT_MONEYTRANSFER = dml("SQL_INSERT_MONEYTRANSFER");
    public static final String SQL_UPSERT_MONEYTRANSFER_FOREIGN = dml("SQL_UPSERT_MONEYTRANSFER_FOREIGN");
    static final String SQL_INSERT_MONEYTRANSFER_PROTOCOL = dml("SQL_INSERT_MONEYTRANSFER_PROTOCOL");
    static final String SQL_INSERT_MONEYTRANSFER_FOREIGN = dml("SQL_INSERT_MONEYTRANSFER_FOREIGN");
    public static final String SQL_INSERT_PARAMETERDATA = dml("SQL_INSERT_PARAMETERDATA");
    public static final String SQL_INSERT_RECIPIENT = dml("SQL_INSERT_RECIPIENT");
    static final String SQL_INSERT_SETTING = dml("SQL_INSERT_SETTING");
    static final String SQL_SELECT_ACCOUNT_LAST_BOOKING_DATE = dml("SQL_SELECT_ACCOUNT_LAST_BOOKING_DATE");
    static final String SQL_SELECT_BANKACCOUNT_RETRIEVAL_STATUS = dml("SQL_SELECT_BANKACCOUNT_RETRIEVAL_STATUS");
    static final String SQL_SELECT_ALL_BANKACCESSES = dml("SQL_SELECT_ALL_BANKACCESSES");
	static final String SQL_SELECT_ALL_PSD2_CLIENT_CONFIGURATIONS = dml("SQL_SELECT_ALL_PSD2_CLIENT_CONFIGURATIONS");
    public static final String SQL_SELECT_ALL_BANKACCOUNTS = dml("SQL_SELECT_ALL_BANKACCOUNTS");
	static final String SQL_SELECT_ALL_BANKACCOUNT_IDENTIFIERS = dml("SQL_SELECT_ALL_BANKACCOUNT_IDENTIFIERS");
	static final String SQL_SELECT_BANKACCOUNT_IDENTIFIERS_BY_ACCOUNT = dml("SQL_SELECT_BANKACCOUNT_IDENTIFIERS_BY_ACCOUNT");
    static final String SQL_SELECT_ALL_BANKACCOUNTS_BY_BANKACCESS = dml("SQL_SELECT_ALL_BANKACCOUNTS_BY_BANKACCESS");
    static final String SQL_SELECT_ALL_BANKACCOUNT_STATEMENTS = dml("SQL_SELECT_ALL_BANKACCOUNT_STATEMENTS");
    static final String SQL_SELECT_ALL_BANKACCOUNT_STATEMENTS_BY_ACCOUNT = dml("SQL_SELECT_ALL_BANKACCOUNT_STATEMENTS_BY_ACCOUNT");
    static final String SQL_SELECT_ALL_BANK_MESSAGES = dml("SQL_SELECT_ALL_BANK_MESSAGES");
    static final String SQL_SELECT_ALL_BANK_MESSAGES_BY_BANKACCESS = dml("SQL_SELECT_ALL_BANK_MESSAGES_BY_BANKACCESS");
    public static final String SQL_SELECT_ALL_BOOKINGS = dml("SQL_SELECT_ALL_BOOKINGS");
    static final String SQL_SELECT_ALL_BOOKINGS_FULL = dml("SQL_SELECT_ALL_BOOKINGS_FULL");
    static final String SQL_SELECT_ALL_BOOKINGS_FULL_BY_ACCOUNT = dml("SQL_SELECT_ALL_BOOKINGS_FULL_BY_ACCOUNT");
    static final String SQL_SELECT_ALL_BOOKINGS_FULL_BY_ACCOUNT_AND_DATE_RANGE = dml("SQL_SELECT_ALL_BOOKINGS_FULL_BY_ACCOUNT_AND_DATE_RANGE");
    static final String SQL_SELECT_SPLIT_BOOKINGS_FULL_BY_PARENT = dml("SQL_SELECT_SPLIT_BOOKINGS_FULL_BY_PARENT");
    static final String SQL_SELECT_ALL_BPD_OR_UPD = dml("SQL_SELECT_ALL_BPD_OR_UPD");
    public static final String SQL_SELECT_ALL_BUSINESSCASES = dml("SQL_SELECT_ALL_BUSINESSCASES");
    public static final String SQL_SELECT_ALL_BUSINESSCASES_BY_BANKACCOUNT = dml("SQL_SELECT_ALL_BUSINESSCASES_BY_BANKACCOUNT");
    static final String SQL_SELECT_ALL_CATEGORIES_FULL = dml("SQL_SELECT_ALL_CATEGORIES_FULL");
    static final String SQL_SELECT_ALL_CATEGORYRULES_FULL = dml("SQL_SELECT_ALL_CATEGORYRULES_FULL");
    public static final String SQL_SELECT_BANKACCOUNTS_BY_CATEGORYRULE = dml("SQL_SELECT_BANKACCOUNTS_BY_CATEGORYRULE");
    static final String SQL_SELECT_ALL_IMPORT_HISTORY = dml("SQL_SELECT_ALL_IMPORT_HISTORY");
    static final String SQL_SELECT_ALL_INSTITUTES = dml("SQL_SELECT_ALL_INSTITUTES");
    static final String SQL_SELECT_ALL_MONEYTRANSFERS_WITH_RECIPIENTS_BY_ACCOUNT = dml("SQL_SELECT_ALL_MONEYTRANSFERS_WITH_RECIPIENTS_BY_ACCOUNT");
    static final String SQL_SELECT_ALL_MONEYTRANSFERS_WITH_RECIPIENTS_BY_ACCOUNT_AND_STATE = dml("SQL_SELECT_ALL_MONEYTRANSFERS_WITH_RECIPIENTS_BY_ACCOUNT_AND_STATE");
    static final String SQL_SELECT_ALL_MONEYTRANSFERS_WITH_RECIPIENTS_BY_STATE = dml("SQL_SELECT_ALL_MONEYTRANSFERS_WITH_RECIPIENTS_BY_STATE");
    static final String SQL_SELECT_MONEYTRANSFER_FOREIGN_BY_MONEYTRANSFER = dml("SQL_SELECT_MONEYTRANSFER_FOREIGN_BY_MONEYTRANSFER");
    static final String SQL_SELECT_ID_MONEYTRANSFER_FOREIGN_BY_MONEYTRANSFER = dml("SQL_SELECT_ID_MONEYTRANSFER_FOREIGN_BY_MONEYTRANSFER");
    static final String SQL_SELECT_ALL_MONEYTRANSFER_PROTOCOLS = dml("SQL_SELECT_ALL_MONEYTRANSFER_PROTOCOLS");
    static final String SQL_SELECT_ALL_MONEYTRANSFER_PROTOCOLS_BY_MONEYTRANSFER = dml("SQL_SELECT_ALL_MONEYTRANSFER_PROTOCOLS_BY_MONEYTRANSFER");
    static final String SQL_SELECT_ALL_PARAMETERDATA = dml("SQL_SELECT_ALL_PARAMETERDATA");
    public static final String SQL_SELECT_ALL_PARAMETERDATA_BY_BANKACCESS = dml("SQL_SELECT_ALL_PARAMETERDATA_BY_BANKACCESS");
    static final String SQL_SELECT_ALL_RECIPIENTS = dml("SQL_SELECT_ALL_RECIPIENTS");
    static final String SQL_SELECT_ALL_RECIPIENTS_WITH_NAME_IBAN = dml("SQL_SELECT_ALL_RECIPIENTS_WITH_NAME_IBAN");
	static final String SQL_SELECT_ALL_RECIPIENTS_ORDERED_MT = dml("SQL_SELECT_ALL_RECIPIENTS_ORDERED_MT");
    public static final String SQL_SELECT_RECIPIENT_CANDIDATES_BY_ACCOUNT_IDENTIFIER = dml("SQL_SELECT_RECIPIENT_CANDIDATES_BY_ACCOUNT_IDENTIFIER");
    public static final String SQL_SELECT_RECIPIENT_BY_ID_IF_EDITABLE = dml("SQL_SELECT_RECIPIENT_BY_ID_IF_EDITABLE");
    static final String SQL_SELECT_PREFERRED_RECIPIENT_BY_IBAN = dml("SQL_SELECT_PREFERRED_RECIPIENT_BY_IBAN");
    public static final String SQL_SELECT_UNREFERENCED_RECIPIENT_CANDIDATES_BY_ACCOUNT_IDENTIFIER = dml("SQL_SELECT_UNREFERENCED_RECIPIENT_CANDIDATES_BY_ACCOUNT_IDENTIFIER");
    static final String SQL_SELECT_ALL_SETTINGS = dml("SQL_SELECT_ALL_SETTINGS");
    public static final String SQL_SELECT_BANKACCESS_BY_BLZ = dml("SQL_SELECT_BANKACCESS_BY_BLZ");
    public static final String SQL_SELECT_BANKACCESS_BY_BLZ_AND_USER_ID = dml("SQL_SELECT_BANKACCESS_BY_BLZ_AND_USER_ID");
    public static final String SQL_SELECT_BANKACCESS_BY_ID = dml("SQL_SELECT_BANKACCESS_BY_ID");
	public static final String SQL_SELECT_BANKACCESS_PAYPAL_BY_USER_ID = dml("SQL_SELECT_BANKACCESS_PAYPAL_BY_USER_ID");
    static final String SQL_SELECT_ID_BANKACCESS_BY_BLZ = dml("SQL_SELECT_ID_BANKACCESS_BY_BLZ");
	static final String SQL_SELECT_ID_PSD2_CLIENT_CONFIGURATION = dml("SQL_SELECT_ID_PSD2_CLIENT_CONFIGURATION");
    static final String SQL_SELECT_ID_BANKACCOUNT_BY_IBAN_OR_NUMBER = dml("SQL_SELECT_ID_BANKACCOUNT_BY_IBAN_OR_NUMBER");
    static final String SQL_SELECT_ID_BANKACCOUNT_STATEMENT_BY_ID = dml("SQL_SELECT_ID_BANKACCOUNT_STATEMENT_BY_ID");
    static final String SQL_SELECT_ID_BANK_MESSAGE_BY_ID = dml("SQL_SELECT_ID_BANK_MESSAGE_BY_ID");
    static final String SQL_SELECT_ID_CATEGORYRULE = dml("SQL_SELECT_ID_CATEGORYRULE");
    static final String SQL_SELECT_ID_CATEGORY_BY_NAME = dml("SQL_SELECT_ID_CATEGORY_BY_NAME");
    static final String SQL_SELECT_ID_IMPORT_HISTORY_BY_ID = dml("SQL_SELECT_ID_IMPORT_HISTORY_BY_ID");
    static final String SQL_SELECT_ID_INSTIUTE_BY_ID = dml("SQL_SELECT_ID_INSTIUTE_BY_ID");
    static final String SQL_SELECT_ID_MONEYTRANSFER_BY_ID_AND_ACCOUNT_ID = dml("SQL_SELECT_ID_MONEYTRANSFER_BY_ID_AND_ACCOUNT_ID");
    static final String SQL_SELECT_ID_SETTING_BY_ID = dml("SQL_SELECT_ID_SETTING_BY_ID");
    public static final String SQL_SELECT_RECIPIENT_BY_ID_IF_NOT_REFERENCED = dml("SQL_SELECT_RECIPIENT_BY_ID_IF_NOT_REFERENCED");
    public static final String SQL_DELETE_ALL_BANKACCESS_PARAMETERDATA_BY_BANKACCESS = dml("SQL_DELETE_ALL_BANKACCESS_PARAMETERDATA_BY_BANKACCESS");
    public static final String SQL_DELETE_UNUSED_PARAMETERDATA = dml("SQL_DELETE_UNUSED_PARAMETERDATA");
    static final String SQL_DELETE_BOOKING = dml("SQL_DELETE_BOOKING");
	static final String SQL_DELETE_BANKACCOUNT_IDENTIFIERS_BY_ACCOUNT = dml("SQL_DELETE_BANKACCOUNT_IDENTIFIERS_BY_ACCOUNT");
    public static final String SQL_DELETE_BOOKING_ADDITIONAL = dml("SQL_DELETE_BOOKING_ADDITIONAL");
	public static final String SQL_DELETE_BOOKING_ADDITIONAL_NOTE = dml("SQL_DELETE_BOOKING_ADDITIONAL_NOTE");
	public static final String SQL_DELETE_BOOKING_ADDITIONAL_CREDITCARD = dml("SQL_DELETE_BOOKING_ADDITIONAL_CREDITCARD");
	public static final String SQL_DELETE_BOOKING_ADDITIONAL_FOREIGNCURRENCY = dml("SQL_DELETE_BOOKING_ADDITIONAL_FOREIGNCURRENCY");
	public static final String SQL_DELETE_BOOKING_FEE = dml("SQL_DELETE_BOOKING_FEE");
	public static final String SQL_DELETE_BOOKING_ADDITIONAL_SEPA = dml("SQL_DELETE_BOOKING_ADDITIONAL_SEPA");
    static final String SQL_DELETE_CATEGORY = dml("SQL_DELETE_CATEGORY");
    static final String SQL_UPDATE_BANKACCESS = dml("SQL_UPDATE_BANKACCESS");
	static final String SQL_UPDATE_PSD2_CLIENT_CONFIGURATION = dml("SQL_UPDATE_PSD2_CLIENT_CONFIGURATION");
	public static final String SQL_UPSERT_BANKACCESS_ENABLEBANKING = dml("SQL_UPSERT_BANKACCESS_ENABLEBANKING");
	public static final String SQL_UPSERT_BANKACCESS_FINTS = dml("SQL_UPSERT_BANKACCESS_FINTS");
	public static final String SQL_UPSERT_BANKACCESS_PAYPAL = dml("SQL_UPSERT_BANKACCESS_PAYPAL");
    static final String SQL_UPDATE_BANKACCOUNT = dml("SQL_UPDATE_BANKACCOUNT");
    static final String SQL_UPDATE_BANKACCOUNT_STATEMENT = dml("SQL_UPDATE_BANKACCOUNT_STATEMENT");
    static final String SQL_UPDATE_BANK_MESSAGE = dml("SQL_UPDATE_BANK_MESSAGE");
    static final String SQL_UPDATE_BANKACCOUNT_SOURCE = dml("SQL_UPDATE_BANKACCOUNT_SOURCE");
    static final String SQL_UPDATE_BOOKING = dml("SQL_UPDATE_BOOKING");
    public static final String SQL_UPDATE_BOOKINGS_CATEGORY = dml("SQL_UPDATE_BOOKINGS_CATEGORY");
    public static final String SQL_UPDATE_BOOKINGS_CATEGORY_RULE = dml("SQL_UPDATE_BOOKINGS_CATEGORY_RULE");
    public static final String SQL_CLEAR_BOOKING_CATEGORY = dml("SQL_CLEAR_BOOKING_CATEGORY");
    public static final String SQL_UPDATE_BOOKINGS_RECIPIENT = dml("SQL_UPDATE_BOOKINGS_RECIPIENT");
    public static final String SQL_CLEAR_BOOKING_CROSS_BOOKING_ID = dml("SQL_CLEAR_BOOKING_CROSS_BOOKING_ID");
    static final String SQL_UPDATE_BOOKINGS_SOURCE = dml("SQL_UPDATE_BOOKINGS_SOURCE");
    static final String SQL_UPDATE_CATEGORY = dml("SQL_UPDATE_CATEGORY");
    public static final String SQL_DELETE_CATEGORYRULE_BANKACCOUNT = dml("SQL_DELETE_CATEGORYRULE_BANKACCOUNT");
    static final String SQL_UPDATE_CATEGORYRULE = dml("SQL_UPDATE_CATEGORYRULE");
    static final String SQL_UPDATE_IMPORT_HISTORY = dml("SQL_UPDATE_IMPORT_HISTORY");
    static final String SQL_UPDATE_INSTIUTE = dml("SQL_UPDATE_INSTIUTE");
	public static final String SQL_UPDATE_INSTIUTE_DK = dml("SQL_UPDATE_INSTITUTE_DK");
	public static final String SQL_UPDATE_INSTIUTE_DBB = dml("SQL_UPDATE_INSTITUTE_DBB");
	public static final String SQL_UPDATE_INSTIUTE_EPC = dml("SQL_UPDATE_INSTITUTE_EPC");
	public static final String SQL_UPDATE_INSTIUTE_DBB_REACHABLE = dml("SQL_UPDATE_INSTITUTE_DBB_REACHABLE");
	public static final String SQL_UPDATE_INSTIUTE_ADDITIONAL = dml("SQL_UPDATE_INSTITUTE_ADDITIONAL");
    static final String SQL_UPDATE_MONEYTRANSFER = dml("SQL_UPDATE_MONEYTRANSFER");
    static final String SQL_UPDATE_MONEYTRANSFER_FOREIGN = dml("SQL_UPDATE_MONEYTRANSFER_FOREIGN");
    public static final String SQL_DELETE_MONEYTRANSFER_FOREIGN_BY_MONEYTRANSFER = dml("SQL_DELETE_MONEYTRANSFER_FOREIGN_BY_MONEYTRANSFER");
    public static final String SQL_UPDATE_RECIPIENT = dml("SQL_UPDATE_RECIPIENT");
    public static final String SQL_UPDATE_RECIPIENT_DEFAULT = dml("SQL_UPDATE_RECIPIENT_DEFAULT");
    static final String SQL_UPDATE_SETTING = dml("SQL_UPDATE_SETTING");
    static final String SQL_UPSERT_BANKACCOUNT_RETRIEVAL_STATUS = dml("SQL_UPSERT_BANKACCOUNT_RETRIEVAL_STATUS");

    static final Map<StatementType, String> BANK_ACCESS_SQL = Map.of(
            StatementType.SELECT_ALL, SQL_SELECT_ALL_BANKACCESSES,
            StatementType.SELECT_ID, SQL_SELECT_ID_BANKACCESS_BY_BLZ,
            StatementType.INSERT, SQL_INSERT_BANKACCESS,
            StatementType.UPDATE, SQL_UPDATE_BANKACCESS,
            StatementType.DELETE_BANKACCESS_BY_ID, SQL_DELETE_BANKACCESS_BY_ID);

	static final Map<StatementType, String> PSD2_CLIENT_CONFIGURATION_SQL = Map.of(
			StatementType.SELECT_ALL, SQL_SELECT_ALL_PSD2_CLIENT_CONFIGURATIONS,
			StatementType.SELECT_ID, SQL_SELECT_ID_PSD2_CLIENT_CONFIGURATION,
			StatementType.INSERT, SQL_INSERT_PSD2_CLIENT_CONFIGURATION,
			StatementType.UPDATE, SQL_UPDATE_PSD2_CLIENT_CONFIGURATION);

    static final Map<StatementType, String> BANK_ACCOUNT_SQL = Map.of(
            StatementType.SELECT_ALL, SQL_SELECT_ALL_BANKACCOUNTS,
            StatementType.SELECT_WITH_PARENT, SQL_SELECT_ALL_BANKACCOUNTS_BY_BANKACCESS,
            StatementType.SELECT_ID, SQL_SELECT_ID_BANKACCOUNT_BY_IBAN_OR_NUMBER,
            StatementType.SELECT_FULL_DATA, SQL_SELECT_ALL_BANKACCOUNTS,
            StatementType.INSERT, SQL_INSERT_BANKACCOUNT,
            StatementType.UPDATE, SQL_UPDATE_BANKACCOUNT,
            StatementType.SELECT_ACCOUNT_LAST_BOOKING_DATE, SQL_SELECT_ACCOUNT_LAST_BOOKING_DATE,
            StatementType.UPDATE_ACCOUNT_SOURCE, SQL_UPDATE_BANKACCOUNT_SOURCE);

    static final Map<StatementType, String> BANK_ACCOUNT_STATEMENT_SQL = Map.of(
            StatementType.SELECT_ALL, SQL_SELECT_ALL_BANKACCOUNT_STATEMENTS,
            StatementType.SELECT_WITH_PARENT, SQL_SELECT_ALL_BANKACCOUNT_STATEMENTS_BY_ACCOUNT,
            StatementType.SELECT_WITH_PARENT_AND_FULL_DATA, SQL_SELECT_ALL_BANKACCOUNT_STATEMENTS_BY_ACCOUNT,
            StatementType.SELECT_ID, SQL_SELECT_ID_BANKACCOUNT_STATEMENT_BY_ID,
            StatementType.INSERT, SQL_INSERT_BANKACCOUNT_STATEMENT,
            StatementType.UPDATE, SQL_UPDATE_BANKACCOUNT_STATEMENT);

    static final Map<StatementType, String> BANK_MESSAGE_SQL = Map.of(
            StatementType.SELECT_ALL, SQL_SELECT_ALL_BANK_MESSAGES,
            StatementType.SELECT_WITH_PARENT, SQL_SELECT_ALL_BANK_MESSAGES_BY_BANKACCESS,
            StatementType.SELECT_WITH_PARENT_AND_FULL_DATA, SQL_SELECT_ALL_BANK_MESSAGES_BY_BANKACCESS,
            StatementType.SELECT_ID, SQL_SELECT_ID_BANK_MESSAGE_BY_ID,
            StatementType.INSERT, SQL_INSERT_BANK_MESSAGE,
            StatementType.UPDATE, SQL_UPDATE_BANK_MESSAGE);

    static final Map<StatementType, String> BOOKING_SQL = Map.of(
            StatementType.SELECT_ALL, SQL_SELECT_ALL_BOOKINGS,
            StatementType.SELECT_FULL_DATA, SQL_SELECT_ALL_BOOKINGS_FULL,
            StatementType.SELECT_WITH_PARENT, SQL_SELECT_ALL_BOOKINGS_FULL_BY_ACCOUNT,
            StatementType.SELECT_WITH_PARENT_AND_FULL_DATA, SQL_SELECT_ALL_BOOKINGS_FULL_BY_ACCOUNT,
            StatementType.SELECT_WITH_PARENT_AND_DATE_RANGE, SQL_SELECT_ALL_BOOKINGS_FULL_BY_ACCOUNT_AND_DATE_RANGE,
            StatementType.INSERT, SQL_INSERT_BOOKING,
            StatementType.UPDATE, SQL_UPDATE_BOOKING,
            StatementType.DELETE, SQL_DELETE_BOOKING,
            StatementType.UPDATE_BOOKING_SOURCE, SQL_UPDATE_BOOKINGS_SOURCE);

    static final Map<StatementType, String> CATEGORY_SQL = Map.of(
            StatementType.SELECT_ALL, SQL_SELECT_ALL_CATEGORIES_FULL,
            StatementType.SELECT_ID, SQL_SELECT_ID_CATEGORY_BY_NAME,
            StatementType.SELECT_FIND, SQL_FIND_CATEGORY,
            StatementType.INSERT, SQL_INSERT_CATEGORY,
            StatementType.UPDATE, SQL_UPDATE_CATEGORY,
            StatementType.DELETE, SQL_DELETE_CATEGORY);

    static final Map<StatementType, String> CATEGORY_RULE_SQL = Map.of(
            StatementType.SELECT_ID, SQL_SELECT_ID_CATEGORYRULE,
            StatementType.SELECT_ALL, SQL_SELECT_ALL_CATEGORYRULES_FULL,
            StatementType.SELECT_FULL_DATA, SQL_SELECT_ALL_CATEGORYRULES_FULL,
            StatementType.INSERT, SQL_INSERT_CATEGORYRULE,
            StatementType.UPDATE, SQL_UPDATE_CATEGORYRULE);

    static final Map<StatementType, String> MONEY_TRANSFER_SQL = Map.of(
            StatementType.SELECT_ALL, SQL_SELECT_ALL_MONEYTRANSFERS_WITH_RECIPIENTS_BY_ACCOUNT,
            StatementType.SELECT_WITH_PARENT, SQL_SELECT_ALL_MONEYTRANSFERS_WITH_RECIPIENTS_BY_ACCOUNT,
            StatementType.SELECT_FULL_DATA, SQL_SELECT_ALL_MONEYTRANSFERS_WITH_RECIPIENTS_BY_STATE,
			StatementType.SELECT_WITH_FILTER, SQL_SELECT_ALL_MONEYTRANSFERS_WITH_RECIPIENTS_BY_STATE,
            StatementType.SELECT_WITH_PARENT_AND_FILTER, SQL_SELECT_ALL_MONEYTRANSFERS_WITH_RECIPIENTS_BY_ACCOUNT_AND_STATE,
            StatementType.SELECT_ID, SQL_SELECT_ID_MONEYTRANSFER_BY_ID_AND_ACCOUNT_ID,
            StatementType.INSERT, SQL_INSERT_MONEYTRANSFER,
            StatementType.UPDATE, SQL_UPDATE_MONEYTRANSFER);

    static final Map<StatementType, String> MONEY_TRANSFER_PROTOCOL_SQL = Map.of(
            StatementType.SELECT_ALL, SQL_SELECT_ALL_MONEYTRANSFER_PROTOCOLS,
            StatementType.SELECT_WITH_PARENT, SQL_SELECT_ALL_MONEYTRANSFER_PROTOCOLS_BY_MONEYTRANSFER,
            StatementType.INSERT, SQL_INSERT_MONEYTRANSFER_PROTOCOL);

    static final Map<StatementType, String> MONEY_TRANSFER_FOREIGN_SQL = Map.of(
            StatementType.SELECT_WITH_PARENT, SQL_SELECT_MONEYTRANSFER_FOREIGN_BY_MONEYTRANSFER,
            StatementType.SELECT_ID, SQL_SELECT_ID_MONEYTRANSFER_FOREIGN_BY_MONEYTRANSFER,
            StatementType.INSERT, SQL_INSERT_MONEYTRANSFER_FOREIGN,
            StatementType.UPDATE, SQL_UPDATE_MONEYTRANSFER_FOREIGN,
            StatementType.DELETE, SQL_DELETE_MONEYTRANSFER_FOREIGN_BY_MONEYTRANSFER);

    static final Map<StatementType, String> RECIPIENT_SQL = Map.of(
            StatementType.SELECT_ALL, SQL_SELECT_ALL_RECIPIENTS,
            StatementType.SELECT_FULL_DATA, SQL_SELECT_ALL_RECIPIENTS_WITH_NAME_IBAN,
            StatementType.SELECT_FIND, SQL_FIND_RECIPIENT_BY_ARGS,
            StatementType.SELECT_SPECIFIC_EDITABLE, SQL_SELECT_RECIPIENT_BY_ID_IF_EDITABLE,
            StatementType.SELECT_SPECIFIC_DELETABLE, SQL_SELECT_RECIPIENT_BY_ID_IF_NOT_REFERENCED,
            StatementType.INSERT, SQL_INSERT_RECIPIENT,
            StatementType.UPDATE, SQL_UPDATE_RECIPIENT);

    static final Map<StatementType, String> PARAMETER_DATA_SQL = Map.of(
            StatementType.SELECT_ALL, SQL_SELECT_ALL_PARAMETERDATA,
            StatementType.INSERT, SQL_INSERT_PARAMETERDATA);

    static final Map<StatementType, String> BPD_SQL = Map.of(
            StatementType.SELECT_ALL, String.format(SQL_SELECT_ALL_BPD_OR_UPD, ParameterDataType.BPD.name()),
            StatementType.SELECT_WITH_PARENT, String.format(SQL_SELECT_ALL_PARAMETERDATA_BY_BANKACCESS, ParameterDataType.BPD.name()));

    static final Map<StatementType, String> UPD_SQL = Map.of(
            StatementType.SELECT_ALL, String.format(SQL_SELECT_ALL_BPD_OR_UPD, ParameterDataType.UPD.name()),
            StatementType.SELECT_WITH_PARENT, String.format(SQL_SELECT_ALL_PARAMETERDATA_BY_BANKACCESS, ParameterDataType.UPD.name()));

    static final Map<StatementType, String> INSTITUTE_SQL = Map.of(
            StatementType.SELECT_ALL, SQL_SELECT_ALL_INSTITUTES,
            StatementType.SELECT_ID, SQL_SELECT_ID_INSTIUTE_BY_ID,
            StatementType.INSERT, SQL_INSERT_INSTIUTE,
            StatementType.UPDATE, SQL_UPDATE_INSTIUTE);

    static final Map<StatementType, String> IMPORT_HISTORY_SQL = Map.of(
            StatementType.SELECT_ALL, SQL_SELECT_ALL_IMPORT_HISTORY,
            StatementType.SELECT_ID, SQL_SELECT_ID_IMPORT_HISTORY_BY_ID,
            StatementType.INSERT, SQL_INSERT_IMPORT_HISTORY,
            StatementType.UPDATE, SQL_UPDATE_IMPORT_HISTORY);

    static final Map<StatementType, String> SETTING_SQL = Map.of(
            StatementType.SELECT_ALL, SQL_SELECT_ALL_SETTINGS,
            StatementType.SELECT_ID, SQL_SELECT_ID_SETTING_BY_ID,
            StatementType.INSERT, SQL_INSERT_SETTING,
            StatementType.UPDATE, SQL_UPDATE_SETTING);

    static final Map<StatementType, String> BUSINESS_CASE_SQL = Map.of(
            StatementType.SELECT_ALL, SQL_SELECT_ALL_BUSINESSCASES,
            StatementType.SELECT_WITH_PARENT, SQL_SELECT_ALL_BUSINESSCASES_BY_BANKACCOUNT,
            StatementType.INSERT, SQL_INSERT_BUSINESSCASE);

    static final Map<StatementType, String> MN_DAO_SQL = Map.of(
            StatementType.INSERT, SQL_INSERT_CATEGORYRULE_BANKACCOUNT);
}
